### ISSUE TITLE
JSON support request

### ISSUE THREAD

**Issue by omarzl** [signalfx/signalflow-cli#10]
It would be useful to export the data to json so the information can be shared to other tools programatically.
There is the timeserieswindow API endpoint https://dev.splunk.com/observability/reference/api/retrieve_timeserieswindow/latest#endpoint-retrieve-mts but the query can't be fully customized, for example the rollup can't be defined, so the best alternative is this cli but it only exports to csv.

**Comment by mpetazzoni** [comment]
You can easily pipe the CSV output into some `csv2json` utility, for example https://github.com/oplatek/csv2json.
